version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: poll_db
      MYSQL_USER: polluser
      MYSQL_PASSWORD: pollpass
    ports:
      - "3306:3306"
    volumes:
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  backend:
    build: ./backend
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: poll_db
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend 